In [5]:
import numpy as np

a = np.array([[1,2,3],[12.2,2,1]])
print(a)

[[ 1.   2.   3. ]
 [12.2  2.   1. ]]


In [7]:
print(a.ndim)
a.shape

2


(2, 3)

In [8]:
a.dtype

dtype('float64')

In [9]:
a[1,2]

1.0

In [10]:
a[1,-1]

1.0

In [11]:
a[0,:]

array([1., 2., 3.])

In [12]:
a[:,:]

array([[ 1. ,  2. ,  3. ],
       [12.2,  2. ,  1. ]])

In [14]:
a[0,1:2:1] #startindex:endindex:stepsize

array([2.])

In [19]:
a[:,2] = [34,35]
a[:,2]  =34
print(a)

[[ 1.   2.  34. ]
 [12.2  2.  34. ]]


In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.ones((4,2), dtype="int32")

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [24]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [25]:
np.random.rand(4,2)

array([[0.38679791, 0.77965149],
       [0.76342293, 0.29044846],
       [0.33482017, 0.92263809],
       [0.54140362, 0.05325858]])

In [28]:
np.random.randint(2,7,size=(3,3))

array([[2, 3, 4],
       [4, 5, 2],
       [3, 3, 3]])

In [29]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
a=np.full((5,5),1)
a[1,1:4] =0 
a[1:4,1] =0 
a[1:4,-2] =0 
a[-2,1:4]=0
a[2,2] =9

In [40]:
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [42]:
a = np.array([1,2,3])
b=a
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [43]:
a = np.array([1,2,3])
b=a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


In [44]:
a=np.array([1,2,3,4,5])
a+2

array([3, 4, 5, 6, 7])

In [46]:
b=np.array([1,2,3,4,5])
a+b

array([ 2,  4,  6,  8, 10])

In [47]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [49]:
a = np.ones((2,3))
b=np.full((3,2),2)

c = np.matmul(a,b)

In [57]:
a = np.random.rand(3,3)

In [62]:
c = np.matmul(a,np.linalg.inv(a))
print(c)

[[ 1.00000000e+00  5.13357104e-17 -8.99397380e-17]
 [ 1.13933695e-16  1.00000000e+00  1.73564268e-17]
 [ 4.94660669e-17 -4.05066526e-17  1.00000000e+00]]


In [63]:
np.min(c)

-8.993973800419346e-17

In [68]:
np.max(c,axis=1)

array([1., 1., 1.])

In [69]:
np.sum(c)

3.0

In [72]:
c.reshape(1,9)

array([[ 1.00000000e+00,  5.13357104e-17, -8.99397380e-17,
         1.13933695e-16,  1.00000000e+00,  1.73564268e-17,
         4.94660669e-17, -4.05066526e-17,  1.00000000e+00]])

In [74]:
c>0.5

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [75]:
c[c>0.5]

array([1., 1., 1.])

In [76]:
np.any(c>0.5,axis=0)

array([ True,  True,  True])

In [77]:
np.all(c>0.5,axis=0)

array([False, False, False])